name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.10", "3.12", "3.13"]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install package (editable) with light extras
        run: |
          pip install -e ".[detect,hardened]"
          pip install pytest

      - name: Lint (optional)
        run: |
          pip install ruff
          ruff --version
          ruff check .

      - name: Run tests
        env:
          NO_COLOR: "1"
          LANG: "C"
          LC_ALL: "C"
        run: |
          pytest

