name: TOC

on:
  push:
    branches: [ main, master ]
    paths:
      - 'README.md'
      - 'README-ES.md'
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  generate-toc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate TOC
        uses: technote-space/toc-generator@v4
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TARGET_PATHS: |
            README.md
            README-ES.md
          MAX_HEADER_LEVEL: 4
          OPENING_COMMENT: '<!-- toc -->'
          CLOSING_COMMENT: '<!-- tocstop -->'
          CREATE_PR: false
          COMMIT_MESSAGE: 'docs: update TOC [skip ci]'

